                                                                                   ; You may customize this and other start-up templates; 
; The location of this template is c:\emu8086\inc\0_com_template.txt

org 100h
.data


PONTEIRO_PALAVRAS DW P0,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,P11,P12,P13,P14,P15,P16,P17,P18,P19,P20,P21,P22,P23,P24,P25,P26,P27,P28
P0  DB "ELETROCARDIOGRAMA","!"
P1  DB "OBITO","!"
P2  DB "ANDADOR","!"
P3  DB "CAMA","!"
P4  DB "PRONTOSOCORRO","!"
P5  DB "COPEIRO","!"
P6  DB "ELETROCARDIOGRAMA","!"
P7  DB "ELEVADOR","!"
P8  DB "PRONTOSOCORRO","!"
P9  DB "OBITO","!"
P10 DB "INJECAO","!"
P11 DB "LABORATORIO","!"
P12 DB "LANCHONETE","!"
P13 DB "MACA","!"
P14 DB "MULETA","!"
P15 DB "PACIENTE","!"
P16 DB "PARTO","!"
P17 DB "POLTRONA","!"
P18 DB "PRONTOSOCORRO","!"
P19 DB "PSICOLOGO","!"
P20 DB "RECEITA","!"
P21 DB "RECEPCIONISTA","!"
P22 DB "TELEFONE","!"
P23 DB "TOMOGRAFIA","!"
P24 DB "TRANSFUSAODESANGUE","!"
P25 DB "VELORIO","!"
P26 DB "VISITANTE","!"
P27 DB "OBITO","!"
P28 DB 7,"FINAL","!"


INICIO_A:
DB "!CAMAxxxxxxCAOX0ROTAAOBALTEACETxxxxxxxxxx!"  
DB "!AAxxxxxxxxOACARTSINIMDAMLEATLExxxxxxxxxx!" 
DB "!MxMxxxxxxxFETPRONTOSOAORROEOELxxxxxxxxxx!"
DB "!AxxAxxxxxxTOUTITDTSOIECOOOOMTExxxxxxxxxx!"
DB "!xxxxxxxxxxDAEGANDADORSSNVBMORFxxxxxxxxxx!"
DB "!xxxxxxxxxxEAMTNLGEVREEIMIIAGOOxxxxxxxxxx!"
DB "!xxxxxxxxxxETEBEAORIEPOCAETIRCNxxxxxxxxxx!"
DB "!xxxxxxxxxxREASUNSOFRLAOVTONAAExxxxxxxxxx!"
DB "!xxxxxxxxxxELLVOLOEISAELDNFJFRVxxxxxxxxxx!"
DB "!xxxxxxxxxxCUSAMTAHDRINOEAAEIDPxxxxxxxxxx!"
DB "!xxxxxxxxxxEMRHDMETCOOIGTTRCAIOxxxxxxxxxx!"
DB "!xxxxxxxxxxPCAIAOAMONALOMIMAJOLxxxxxxxxxx!"
DB "!xxxxxxxxxxCAICDDSAERASEOSAOEGTxxxxxxxxxx!"
DB "!xxxxxxxxxxIPCSSCERIRILUVICASRRxxxxxxxxxx!"
DB "!xxxxxxxxxxOEAIIMEETOGOMFVIRTAOxxxxxxxxxx!"
DB "!xxxxxxxxxxNLAUECESGPDEEUSAADMNxxxxxxxxxx!"
DB "!xxxxxxxxxxIADDENISUAMSNTSNMNAAxxxxxxxxxx!"
DB "!xxxxxxxxxxSETIRRTLARSQCCCEAERAxxxxxxxxxx!"
DB "!xxxxxxxxxxTMTSANAETTCERAIACRAOxxxxxxxxxx!"	
DB "!xxxxxxxxxxAARMASMRGOOTGIEAARTTxxxxxxxxxx!#",0




mens1 db "A substring n?o se encontra no caca-palavras",0
        
;MIGUEL DB tamanho DUP(" "),0

ARRAY DW 0,0,0,0,0,0

VARIAVEL1 DW 0
VARIAVEL2 DW 0
VARIAVEL3 DW 0 
VARIAVEL4 DW 0
VARIAVEL5 DW 0
VARIAVEL6 DW 0
VARIAVEL7 DW 0
VARIAVEL8 DW 0
VARIAVEL9 DW 0 
VARIAVEL10 DW 0
VARIAVEL11 DW 0
VARIAVEL12 DW 0                                                       
VARIAVEL13 DW 0
VARIAVEL14 DW 0
VARIAVEL15 DW 0 
VARIAVEL16 DW 0
VARIAVEL17 DW 0
VARIAVEL18 DW 0
VARIAVEL19 DW 0
VARIAVEL20 DW 0

PALAVRA DB "-------------------",0

PLACEHOLDERC DW 0

PLACEHOLDERA DW 0

PLACEHOLDERSI DW 0

PLACEHOLDERDI DW 0

POINTERC DW  0 ; aponta para o endere?o de memoria do INICIO_C

PRINTPLACEHOLDER DW 6;
PRINTPLACEHOLDER1 DW 0

CONTADOR DW 0 



DB 0,"#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$!"     





INICIO_C:
DB "!----------------------------------------!"
DB "!----------------------------------------!"
DB "!----------------------------------------!"    
DB "!----------------------------------------!"
DB "!----------------------------------------!"       ;k-l  
DB "!----------------------------------------!"
DB "!----------------------------------------!"  ;aqui
DB "!----------------------------------------!"
DB "!----------------------------------------!"
DB "!----------------------------------------!"
DB "!----------------------------------------!"
DB "!----------------------------------------!"
DB "!----------------------------------------!"
DB "!----------------------------------------!"
DB "!----------------------------------------!"
DB "!----------------------------------------!"
DB "!----------------------------------------!"
DB "!----------------------------------------!"
DB "!----------------------------------------!"
DB "!----------------------------------------!#","#"




.code

; add your code here    
MOV BX,0 ; INDICE = X = PX                              
;eh necessario ir incrementando de 2 em 2
loop:                          
MOV CONTADOR,0
MOV SI,PONTEIRO_PALAVRAS[BX]
MOV AH,[SI]
CMP AH,7
JE IMPRIMEDB
MOV DI,OFFSET PALAVRA
CALL PERCORRERPALAVRA
CALL CACAPALAVRA
JMP LOOP1




PERCORRERPALAVRA: 
mov CH,[SI]
MOV [DI],CH
INC DI
INC CONTADOR
CMP CH,"!"

JNE PERCORRERPALAVRA1
DEC DI
MOV [DI],0
RET

PERCORRERPALAVRA1:
mov CH,[SI]
CMP CH,0
JE FIM
INC SI
JMP PERCORRERPALAVRA

LOOP1:
;CALL CACAPALAVRA
MOV POINTERC,0
ADD BX,2
JMP LOOP


inc si
mov ch,[si]                          


; SI VAI TER O ENDERECO DE P0
; SI = 20

MOV BX,2 ; INDICE = X = PX <-------------------------------PATCH                            
MOV SI,PONTEIRO_PALAVRAS[BX]
; SI VAI TER O ENDERECO DE P1 
; SI = 34                             



jmp $         

CACAPALAVRA1:
RET
CACAPALAVRA:
; puxando todos os registradores e as flags para a pilha, para garantir a integridade de dados
PUSH AX
PUSH BX
PUSH CX
PUSH DX
PUSH DI
PUSH SI
PUSHF

MOV SI,OFFSET PALAVRA
MOV DI,OFFSET INICIO_A  ;movendo o endere?o de mem?ria destas variaveis para os registradores

PUSH DI
MOV DI,OFFSET INICIO_C
MOV POINTERC,DI
POP DI 

PROXIMALETRA:
INC POINTERC ;incrementando para apontar a primeira letra do ca?a-palavra 
INC DI 
mov ch,[di] 
mov cl,[si]

CMP ch,cl
JE PRIMEIRALETRA
CMP CH,0
JE FIM
JMP PROXIMALETRA





PRIMEIRALETRA:
CALL GUARDARVALOR
CALL PALAVRAVERTICAL
CALL DEVOLVERVALOR
CALL palavrahorizontal
CALL DEVOLVERVALOR
CALL PALAVRADIAGONAL1
CALL DEVOLVERVALOR
CALL PALAVRADIAGONAL2
CALL DEVOLVERVALOR
CALL PALAVRADIAGONAL3
CALL DEVOLVERVALOR
CALL PALAVRADIAGONAL4
CALL DEVOLVERVALOR
CALL PALAVRAVERTICALMANGA
CALL DEVOLVERVALOR
JMP PROXIMALETRA





PALAVRAVERTICAL1:
INC POINTERC
INC SI
INC DI
MOV CH,[DI]
MOV CL,[SI]
CMP CL,CH
JE PALAVRAVERTICAL 
RET


PALAVRAVERTICAL:
CALL ESCREVERC
JMP PALAVRAVERTICAL1


PALAVRAHORIZONTAL1:

INC SI
ADD DI,42
ADD POINTERC,42
MOV CH,[DI]
MOV CL,[SI]
CMP CH,CL
JE palavrahorizontal
RET


palavrahorizontal:
CALL ESCREVERC
JMP PALAVRAHORIZONTAL1



PALAVRADIAGONAL11:

INC SI
ADD DI,43
ADD POINTERC,43
MOV CH,[DI]
MOV CL,[SI]
CMP CH,CL
JE PALAVRADIAGONAL1
RET


PALAVRADIAGONAL1:
CALL ESCREVERC
JMP PALAVRADIAGONAL11



PALAVRADIAGONAL22:

INC SI
ADD DI,41
ADD POINTERC,41
MOV CH,[DI]
MOV CL,[SI]
CMP CH,CL
JE PALAVRADIAGONAL2
RET


PALAVRADIAGONAL2:
CALL ESCREVERC
JMP PALAVRADIAGONAL22

PALAVRADIAGONAL33:

INC SI
SUB DI,41
SUB POINTERC,41
MOV CH,[DI]
MOV CL,[SI]
CMP CH,CL
JE PALAVRADIAGONAL3
RET


PALAVRADIAGONAL3:
CALL ESCREVERC
JMP PALAVRADIAGONAL33

PALAVRADIAGONAL44:

INC SI
SUB DI,43
SUB POINTERC,43
MOV CH,[DI]
MOV CL,[SI]
CMP CH,CL
JE PALAVRADIAGONAL4
RET


PALAVRADIAGONAL4:
CALL ESCREVERC
JMP PALAVRADIAGONAL44


PALAVRAVERTICALMANGA1:
SUB DI,42
SUB POINTERC,42
INC SI 
MOV CH,[DI]
MOV CL,[SI]
CMP CH,CL
JE SIPERCORRIDO
RET

PALAVRAVERTICALMANGA:
SIPERCORRIDO:
CALL ESCREVERC
JMP PALAVRAVERTICALMANGA1


PERCORRERSI:
INC SI
MOV CH,[SI]
CMP CH,0

JNE PERCORRERSI
JMP SIPERCORRIDO

ESCREVERC:
INC PRINTPLACEHOLDER1
CMP PRINTPLACEHOLDER1,1
JE LETRA1
CMP PRINTPLACEHOLDER1,2
JE LETRA2
CMP PRINTPLACEHOLDER1,3
JE LETRA3
CMP PRINTPLACEHOLDER1,4
JE LETRA4
CMP PRINTPLACEHOLDER1,5
JE LETRA5
CMP PRINTPLACEHOLDER1,6
JE LETRA6
CMP PRINTPLACEHOLDER1,7
JE LETRA7
CMP PRINTPLACEHOLDER1,8
JE LETRA8
CMP PRINTPLACEHOLDER1,9
JE LETRA9
CMP PRINTPLACEHOLDER1,10
JE LETRA10
CMP PRINTPLACEHOLDER1,11
JE LETRA11
CMP PRINTPLACEHOLDER1,12
JE LETRA12
CMP PRINTPLACEHOLDER1,13
JE LETRA13
CMP PRINTPLACEHOLDER1,14
JE LETRA14
CMP PRINTPLACEHOLDER1,15
JE LETRA15
CMP PRINTPLACEHOLDER1,16
JE LETRA16
CMP PRINTPLACEHOLDER1,17
JE LETRA17
CMP PRINTPLACEHOLDER1,18
JE LETRA18
CMP PRINTPLACEHOLDER1,19
JE LETRA19
CMP PRINTPLACEHOLDER1,20
JE LETRA20





LETRA1:
PUSH DI
MOV DI, POINTERC
MOV VARIAVEL1,DI
POP DI
RET

LETRA2:
PUSH DI
MOV DI, POINTERC
MOV VARIAVEL2,DI
POP DI
RET

LETRA3:
PUSH DI
MOV DI, POINTERC
MOV VARIAVEL3,DI
POP DI
RET

LETRA4:
PUSH DI
MOV DI, POINTERC
MOV VARIAVEL4,DI
POP DI
PUSH AX
MOV AX,CONTADOR
DEC AX
CMP PRINTPLACEHOLDER1,AX
POP AX
JE INSERIRPALAVRA 
RET

LETRA5:
PUSH DI
MOV DI, POINTERC
MOV VARIAVEL5,DI
POP DI
PUSH AX
MOV AX,CONTADOR
DEC AX
CMP PRINTPLACEHOLDER1,AX
POP AX
JE INSERIRPALAVRA
RET

LETRA6:
PUSH DI
MOV DI, POINTERC
MOV VARIAVEL6,DI
POP DI
PUSH AX
MOV AX,CONTADOR
DEC AX
CMP PRINTPLACEHOLDER1,AX
POP AX
JE INSERIRPALAVRA
RET

LETRA7:
PUSH DI
MOV DI, POINTERC
MOV VARIAVEL7,DI
POP DI
PUSH AX
MOV AX,CONTADOR
DEC AX
CMP PRINTPLACEHOLDER1,AX
POP AX
JE INSERIRPALAVRA
RET
   
LETRA8:
PUSH DI
MOV DI, POINTERC
MOV VARIAVEL8,DI
POP DI
PUSH AX
MOV AX,CONTADOR
DEC AX
CMP PRINTPLACEHOLDER1,AX
POP AX
JE INSERIRPALAVRA
RET   

LETRA9:
PUSH DI
MOV DI, POINTERC
MOV VARIAVEL9,DI
POP DI
PUSH AX
DEC AX
MOV AX,CONTADOR
CMP PRINTPLACEHOLDER1,AX
POP AX
JE INSERIRPALAVRA
RET

LETRA10:
PUSH DI
MOV DI, POINTERC
MOV VARIAVEL10,DI
POP DI
PUSH AX
MOV AX,CONTADOR
DEC AX
CMP PRINTPLACEHOLDER1,AX
POP AX
JE INSERIRPALAVRA
RET

LETRA11:
PUSH DI
MOV DI, POINTERC
MOV VARIAVEL11,DI
POP DI
PUSH AX
MOV AX,CONTADOR
DEC AX
CMP PRINTPLACEHOLDER1,AX
POP AX
JE INSERIRPALAVRA
RET


LETRA12:
PUSH DI
MOV DI, POINTERC
MOV VARIAVEL12,DI
POP DI
PUSH AX
MOV AX,CONTADOR
DEC AX
CMP PRINTPLACEHOLDER1,AX
POP AX
JE INSERIRPALAVRA
RET

LETRA13:
PUSH DI
MOV DI, POINTERC
MOV VARIAVEL13,DI
POP DI
PUSH AX
MOV AX,CONTADOR
DEC AX
CMP PRINTPLACEHOLDER1,AX
POP AX
JE INSERIRPALAVRA
RET

LETRA14:
PUSH DI
MOV DI, POINTERC
MOV VARIAVEL14,DI
POP DI
PUSH AX
MOV AX,CONTADOR
DEC AX
CMP PRINTPLACEHOLDER1,AX
POP AX
JE INSERIRPALAVRA
RET

LETRA15:
PUSH DI
MOV DI, POINTERC
MOV VARIAVEL15,DI
POP DI
PUSH AX
MOV AX,CONTADOR
DEC AX
CMP PRINTPLACEHOLDER1,AX
POP AX
JE INSERIRPALAVRA
RET

LETRA16:
PUSH DI
MOV DI, POINTERC
MOV VARIAVEL16,DI
POP DI
PUSH AX
MOV AX,CONTADOR
DEC AX
CMP PRINTPLACEHOLDER1,AX
POP AX
JE INSERIRPALAVRA
RET

LETRA17:
PUSH DI
MOV DI, POINTERC
MOV VARIAVEL17,DI
POP DI
PUSH AX
MOV AX,CONTADOR
DEC AX
CMP PRINTPLACEHOLDER1,AX
POP AX
JE INSERIRPALAVRA
RET

LETRA18:
PUSH DI
MOV DI, POINTERC
MOV VARIAVEL18,DI
POP DI
PUSH AX
MOV AX,CONTADOR
DEC AX
CMP PRINTPLACEHOLDER1,AX
POP AX
JE INSERIRPALAVRA
RET

LETRA19:
PUSH DI
MOV DI, POINTERC
MOV VARIAVEL19,DI
POP DI
PUSH AX
MOV AX,CONTADOR
DEC AX
CMP PRINTPLACEHOLDER1,AX
POP AX
JE INSERIRPALAVRA
RET

LETRA20:
PUSH DI
MOV DI, POINTERC
MOV VARIAVEL20,DI
POP DI
PUSH AX
MOV AX,CONTADOR
DEC AX
CMP PRINTPLACEHOLDER1,AX
POP AX
JE INSERIRPALAVRA
RET




INSERIRPALAVRA:
MOV PRINTPLACEHOLDER1,2
MOV SI,OFFSET PALAVRA
MOV CH,[SI]

PUSH DI
MOV DI, VARIAVEL1
MOV [DI],CH
POP DI

INC SI
INC PRINTPLACEHOLDER1
MOV CH,[SI]

PUSH DI
MOV DI, VARIAVEL2
MOV [DI],CH
POP DI


INC SI
INC PRINTPLACEHOLDER1
MOV CH,[SI]

PUSH DI
MOV DI, VARIAVEL3
MOV [DI],CH
POP DI


INC SI 
INC PRINTPLACEHOLDER1
MOV CH,[SI]

PUSH DI
MOV DI, VARIAVEL4
MOV [DI],CH
POP DI
PUSH AX
MOV AX,CONTADOR
CMP PRINTPLACEHOLDER1,AX
JE FIMPALAVRAINSERIDA
POP AX



INC SI
INC PRINTPLACEHOLDER1
MOV CH,[SI]

PUSH DI
MOV DI, VARIAVEL5
MOV [DI],CH
POP DI
PUSH AX
MOV AX,CONTADOR
CMP PRINTPLACEHOLDER1,AX
JE FIMPALAVRAINSERIDA
POP AX

INC SI 
INC PRINTPLACEHOLDER
MOV CH,[SI]

PUSH DI
MOV DI, VARIAVEL6
MOV [DI],CH
POP DI
PUSH AX
MOV AX,CONTADOR
CMP PRINTPLACEHOLDER1,AX
JE FIMPALAVRAINSERIDA
POP AX

INC SI
INC PRINTPLACEHOLDER1
MOV CH,[SI]


PUSH DI
MOV DI, VARIAVEL7
MOV [DI],CH
POP DI
PUSH AX
MOV AX,CONTADOR
CMP PRINTPLACEHOLDER1,AX
JE FIMPALAVRAINSERIDA
POP AX

INC SI
INC PRINTPLACEHOLDER1
MOV CH,[SI]

PUSH DI
MOV DI, VARIAVEL8
MOV [DI],CH
POP DI
PUSH AX
MOV AX,CONTADOR
CMP PRINTPLACEHOLDER1,AX
JE FIMPALAVRAINSERIDA 
POP AX

INC SI
INC PRINTPLACEHOLDER1
MOV CH,[SI]

PUSH DI
MOV DI, VARIAVEL9
MOV [DI],CH
POP DI
PUSH AX
MOV AX,CONTADOR
CMP PRINTPLACEHOLDER1,AX
JE FIMPALAVRAINSERIDA
POP AX

INC SI
INC PRINTPLACEHOLDER1
MOV CH,[SI]

PUSH DI
MOV DI, VARIAVEL10
MOV [DI],CH
POP DI
PUSH AX
MOV AX,CONTADOR
CMP PRINTPLACEHOLDER1,AX
JE FIMPALAVRAINSERIDA
POP AX

INC SI
INC PRINTPLACEHOLDER1
MOV CH,[SI]

PUSH DI
MOV DI, VARIAVEL11
MOV [DI],CH
POP DI
PUSH AX
MOV AX,CONTADOR
CMP PRINTPLACEHOLDER1,AX
JE FIMPALAVRAINSERIDA 
POP AX

INC SI
INC PRINTPLACEHOLDER1
MOV CH,[SI]

PUSH DI
MOV DI, VARIAVEL12
MOV [DI],CH
POP DI
PUSH AX
MOV AX,CONTADOR
CMP PRINTPLACEHOLDER1,AX
JE FIMPALAVRAINSERIDA 
POP AX

INC SI
INC PRINTPLACEHOLDER1
MOV CH,[SI]

PUSH DI
MOV DI, VARIAVEL13
MOV [DI],CH
POP DI
PUSH AX
MOV AX,CONTADOR
CMP PRINTPLACEHOLDER1,AX
JE FIMPALAVRAINSERIDA
POP AX
                      
INC SI
INC PRINTPLACEHOLDER1
MOV CH,[SI]

PUSH DI
MOV DI, VARIAVEL14
MOV [DI],CH
POP DI
PUSH AX
MOV AX,CONTADOR
CMP PRINTPLACEHOLDER1,AX
JE FIMPALAVRAINSERIDA                      
POP AX
                      
INC SI
INC PRINTPLACEHOLDER1
MOV CH,[SI]

PUSH DI
MOV DI, VARIAVEL15
MOV [DI],CH
POP DI
PUSH AX
MOV AX,CONTADOR
CMP PRINTPLACEHOLDER1,AX
JE FIMPALAVRAINSERIDA                      
POP AX                      
                      
INC SI
INC PRINTPLACEHOLDER1
MOV CH,[SI]

PUSH DI
MOV DI, VARIAVEL16
MOV [DI],CH
POP DI
PUSH AX
MOV AX,CONTADOR
CMP PRINTPLACEHOLDER1,AX
JE FIMPALAVRAINSERIDA                      
POP AX                      
                      
INC SI
INC PRINTPLACEHOLDER1
MOV CH,[SI]

PUSH DI
MOV DI, VARIAVEL17
MOV [DI],CH
POP DI
PUSH AX
MOV AX,CONTADOR
CMP PRINTPLACEHOLDER1,AX
JE FIMPALAVRAINSERIDA                      
POP AX                      
                      
INC SI
INC PRINTPLACEHOLDER1
MOV CH,[SI]

PUSH DI
MOV DI, VARIAVEL18
MOV [DI],CH
POP DI
PUSH AX
MOV AX,CONTADOR
CMP PRINTPLACEHOLDER1,AX
JE FIMPALAVRAINSERIDA                      
POP AX                      
                      
INC SI
INC PRINTPLACEHOLDER1
MOV CH,[SI]

PUSH DI
MOV DI, VARIAVEL19
MOV [DI],CH
POP DI
PUSH AX
MOV AX,CONTADOR
CMP PRINTPLACEHOLDER1,AX
JE FIMPALAVRAINSERIDA                      
POP AX                      


INC SI
INC PRINTPLACEHOLDER1
MOV CH,[SI]

PUSH DI
MOV DI, VARIAVEL20
MOV [DI],CH
POP DI
PUSH AX
MOV AX,CONTADOR
CMP PRINTPLACEHOLDER1,AX
JE FIMPALAVRAINSERIDA                      
POP AX


FIMPALAVRAINSERIDA:
POP AX
ret

GUARDARVALOR:
MOV PLACEHOLDERSI,SI
MOV PLACEHOLDERDI,DI
MOV PRINTPLACEHOLDER,6
PUSH DI
MOV DI,POINTERC
MOV PLACEHOLDERC,DI
POP DI
RET

DEVOLVERVALOR:
MOV PRINTPLACEHOLDER1,0
MOV SI,PLACEHOLDERSI
MOV DI,PLACEHOLDERDI
mov cl,[si]
mov ch,[di]

MOV PRINTPLACEHOLDER,6
PUSH DI
MOV DI,PLACEHOLDERC
MOV POINTERC,DI
POP DI
RET

PULA_LINHA:                       
pushf
push ax
push dx
MOV AH,2  ; socorro, destruiram ax
MOV DL,13          
INT 21H
MOV AH,2  ; socorro, destruiram ax
MOV DL,10
INT 21H
pop dx          
pop ax
popf
RET

FIM: 
POPF
POP SI
POP DI
POP DX
POP CX
POP BX 
POP AX
RET


IMPRIMEDB:
PUSH AX
PUSH BX
PUSH CX
PUSH DX
PUSH DI
PUSH SI
PUSHF
MOV DI,OFFSET INICIO_C
IMPRIMEDB1:
INC DI
IMPRIMEDB3:
mov ch,[di]
cmp ch,'!'
je IMPRIMEDB2

mov ah,2
mov dl,ch
int 21h
cmp ch,'#'
je FIM1234
JMP IMPRIMEDB1


IMPRIMEDB2:
INC DI
INC DI
CALL PULA_LINHA
jmp imprimedb3


FIM1234:
jmp $

;RELATORIO
;---------
;PROCURANDO PALAVRA "ADMINISTRACAO" - TAMANHO X
;.
;MOSTRAR CACA PALAVRAS
;   
;ESPERAR TECLAR ALGO PARA CONTINUAR...
;PROCURANDO PALAVRA "AMBULATORIO" - TAMANHO X
;.
;MOSTRAR CACA PALAVRAS               
;.
;ESPERAR TECLAR ALGO PARA CONTINUAR.. 


                                                           